name = "video-sync"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVERS"
class_name = "WebSocketServer"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketServer"]

