name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy worker
    steps:
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN  }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
